// ChampionReducer
export const GET_CHAMPION_DATA = 'GET_CHAMPION_DATA';
export const SET_CHAMPION_DATA = 'SET_CHAMPION_DATA';
export const SET_FILTERED_CHAMPIONS = 'SET_FILTERED_CHAMPIONS';


// Live Game reducer
export const SET_SUMMONERDATA = 'SET_SUMMONERDATA';
export const SET_LIVEGAME = 'SET_LIVEGAME';

// Unknown
export const SET_SUMMONER_CHAMPION_DATA = "SET_SUMMONER_CHAMPION_DATA";
export const SET_SUMMONER_LEAGUE_DATA = "SET_SUMMONER_LEAGUE_DATA";

// Static data reducer
export const SET_STATIC_CHAMPIONS = "SET_STATIC_CHAMPIONS";
export const SET_STATIC_RUNES = "SET_STATIC_RUNES";
export const SET_STATIC_MASTERIES = "SET_STATIC_MASTERIES";
export const SET_STATIC_SUMMONER_SPELLS = "SET_STATIC_SUMMONER_SPELLS";
export const SET_STATIC_VERSION = "SET_STATIC_VERSION";