export const STORE_KEY = "AWESOME_LIVE_GAME_LOL_INFO_APP";

export const STATIC_CHAMPIONS = "STATIC_CHAMPIONS";
export const STATIC_RUNES = "STATIC_RUNES";
export const STATIC_MASTERIES = "STATIC_MASTERIES";
export const STATIC_SUMMONER_SPELLS = "STATIC_SUMMONER_SPELLS";

export const VERSION = "VERSION";